import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { required } from "zod/mini";
import { convertTextToPdfUsingPuppeteer } from "./puppeteer.service.js";

const geminiSchema = {
  type: "object",
  properties: {
    title: { type: "string" },
    matchScore: { type: "number" },
    technicalQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    behavioralQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    skillGaps: {
      type: "array",
      items: {
        type: "object",
        properties: {
          skill: { type: "string" },
          severity: { type: "string", enum: ["Low", "Medium", "High"] },
        },
        required: ["skill", "severity"],
      },
    },
    preparationPlan: {
      type: "array",
      items: {
        type: "object",
        properties: {
          day: { type: "number" },
          focus: { type: "string" },
          tasks: { type: "array", items: { type: "string" } },
        },
        required: ["day", "focus", "tasks"],
      },
    },
  },
  required: ["title", "matchScore", "technicalQuestions", "behavioralQuestions", "skillGaps", "preparationPlan"],
};

export const generateInterviewReport = async ({ jobDescription, resume, selfDescription }) => {
  const prompt = `
    Generate an interview report on the basis of given schema for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription} `;

  const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
  })

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        systemInstruction: "Respond with a valid JSON object strictly following the provided response schema. All required fields must be present.",
        responseMimeType: "application/json",
        responseSchema: geminiSchema,
      }
    })

    const interviewReport = JSON.parse(response.text);

    return interviewReport;
  } catch (error) {
    console.error("Error generating interview report:", error);
    throw error;
  }
}

export const generateResumePdf = async ({ jobDescription, resume, selfDescription }) => {
  try {
    const prompt = `Generate a resume in PDF format for a candidate based on the following details:
                    Resume: ${resume}
                    Self Description: ${selfDescription}
                    Job Description: ${jobDescription}
                    
                    the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`;

    const pdfSchema = z.object({
      html: z.string().describe("HTML content of the resume which can be converted to PDF using any library like puppeteer")
    }).describe("Schema for the response of resume PDF generation")

    const ai = new GoogleGenAI({
      apiKey: process.env.GOOGLE_GENAI_API_KEY
    })

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: zodToJsonSchema(pdfSchema)
      }
    })

    const pdfBuffer = await convertTextToPdfUsingPuppeteer(response.text)
    return pdfBuffer;

  } catch (error) {
    console.error("Error generating resume PDF from interview report: ", error);
    throw error;
  }
}

